version: '3.3'
services:
    mongo:
        image: mongo:4.4.7
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=r9hino
            - MONGO_INITDB_ROOT_PASSWORD=31415926=
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=r9hino
            - ME_CONFIG_MONGODB_ADMINPASSWORD=31415926=
            - ME_CONFIG_MONGODB_SERVER=mongo