version: '3.3'
services:
    mongo:
        image: mongo:4.4.7
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=userchange
            - MONGO_INITDB_ROOT_PASSWORD=passchange
    mongo-express:
        image: mongo-express
        restart: always
        ports:
 