# Step needed:
#   - Creating a network: 
#       docker network create --driver bridge influxdb2-telegraf-net
#   - Run Influx DB container, and from there get token for Telegraf.
#   - Configure telegraf.config file:
#       docker run --rm telegraf:latest telegraf config > /home/pi/Code/RPi4Node/ACM/Docker/telegraf/telegraf.conf
#
# https://www.blackvoid.club/grafana-8-influxdb-2-telegraf-2021-monitoring-stack/

version: '3.5'

services:
  telegraf:
    image: telegraf:latest
    env_file:
      - ./.env
    pid: 'host'
    container_name: telegraf
    ports:
      - '8092:8092'
      - '8094:8094'
      - '8125:8125'
    volumes:
      - /home/pi/Code/RPi4Node/ACM/Docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    restart: always
networks:
  default:
    external: true
    name: influxdb2-telegraf-net